# This workflow only meant for the source mod you shouldn't bring it into your own project

name: Buildscript maintenance

on:
  push:
    branches: [ master, main ]
    paths:
      - build.gradle
      - settings.gradle
  workflow_dispatch: { }

jobs:
  buildscript-maintenance:
    runs-on: ubuntu-latest
    # Avoid running this workflow on forks
    if: github.repository == 'GregTechCEu/Buildscripts'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure build script version is up to date
        id: update-buildscript
        run: |
          new_version="$(date +%s)"
          sed --in-place "1s!^//version:.*!//version: $new_version!g" build.gradle
          echo "::set-output name=new_version::$new_version"

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDSCRIPT_MAINTENANCE_TOKEN }}
        with:
          token: ${{ secrets.BUILDSCRIPT_MAINTENANCE_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          add-paths: build.gradle
          commit-message: '[ci skip] update build script version to ${{ steps.update-buildscript.outputs.new_version }}'
          branch: gha-buildscript-maintenance
          title: Update build script version to ${{ steps.update-buildscript.outputs.new_version }}
          body: This pull request is created by the buildscript-maintenance workflow
